### ISSUE TITLE
fail in AfterStep leaves step successful but scenario failed

### ISSUE THREAD

**Issue by rosskevin** [cucumber/cucumber-ruby#1101]
## Summary

```
AfterStep do
   fail 'foo'
end
```

Results in all steps being indicated as passing.

```
1 scenario (1 failed)
7 steps (7 passed)
```

I am trying to indicate a step has failed if I find javascript errors in the after step.  All steps are marked as `passed`, even though I should be able to fail the given step in the `AfterStep` hook.

## Expected Behavior
**When** I run a scenario
**If** I `fail` in an `AfterStep`
**Then** the step should be marked as `failed`.

## Current Behavior
**When** I run a scenario
**If** I `fail` in an `AfterStep`
**Then** the step is left as `passed`.

## Steps to Reproduce (for bugs)

1. Use any scenario
2. Add 
```
AfterStep do
   fail 'foo'
end
```

## Context & Motivation
Visually, especially if it is the last step in the scenario, it is quite confusing to see all steps passed but the scenario fails.

## Your Environment
* Version used: 2.4.0
* Operating System and version: OSX

**Comment by danascheider** [comment]
@brasmusson or @mattwynne is this considered expected behavior?

**Comment by mattwynne** [comment]
I can understand why it happens, but it does seem surprising. The problem is that the way we currently model it, the after-step hook is just another test step in sequence after the gherkin step it was "hooked" onto. So that original gherkin step has already run and passed.

I've been thinking for a while that it would help us to be able to model "nested" steps or sub-steps, as this would also help us get rid of a lot of the edge-cases with around hooks. But this is just vague blue-sky thinking, I don't have anything concrete for how we would do it.

In this case, I wonder if it would be better for now if we were more transparent about the hook steps that are also running, and showing their pass / fail status (or at least their fail status).

Maybe we could include hooks in the summary counts?

e.g.

```
7 steps (7 passed)
4 hooks (3 passed, 1 failed)
```

**Comment by danascheider** [comment]
I like that idea, @mattwynne. I definitely think we could be more transparent about the source of failures coming from hooks, because I've had trouble before figuring out exactly what went wrong in cases like this.

**Comment by brasmusson** [comment]
I doubt that after-step hooks were introduced to do extra verification in addition to the verification in the step definitions, so from that perspective it is not expected behaviour that an failure in an after-step hook fails the step it is after-step hook for. 

Comparing with scenarios and their before and after hooks, we consider both the results of each step definition and hook individually, and combine their results to the result for the scenario (the individual results are clearly documented in the json formatter output). To let an after-step hook fail the step would then mean that we both consider the result of the step definition and the after-step hook(s) individually, and also calculate a result for the step and after-step hook combo. This looks like a major change of the implemented execution model we have today, I don't think it should be considered before Cucumber-Ruby version 4.

**Comment by jaysonesmith** [comment]
I'm on board with @brasmusson 's thoughts here about verification in the after step. I would consider the after to be used for things like cleanup if needed.

**Comment by rosskevin** [comment]
I think there is value in not closing this due to staleness, but if it is deemed not worth fixing, I guess I'll let it go.

**Comment by rosskevin** [comment]
I'm not interested in the effort.  If you view it as enhancement and not a bug, let's close it out.  Please label as an `enhancement` in case this gets resurrected/found later.
