### ISSUE TITLE
When will we bump version 3.0.0?

### ISSUE THREAD

**Issue by junaruga** [cucumber/cucumber-ruby#1118]
## Summary

Hello,
When will we release version 3.0.0?
Do you have tasks to fix before the release?

## Context & Motivation

Current `cucumber` latest stable version is 2.4.0 that uses `cucumber-core` `~> 1.5.0`.
We also released cucumber pre version `3.0.0.pre.1` that uses `cucumber-core` latest version 2.0.0 (`~> 2.0`) at September 02, 2016.

Then 6 months has been passed.
Now I want to use `cucumber-cure` 2 from latest `cucumber` stable version.
It's time to bump version 3.0.0, isn't it?

Ref.
https://rubygems.org/gems/cucumber
https://rubygems.org/gems/cucumber-core

**Comment by mattwynne** [comment]
Wow, I didn't realise it had been that long!

I had been hoping for the [event protocol](https://github.com/cucumber/cucumber/pull/172) to stabilise before we released, because I don't want us to have to introduce breaking changes again later, but I think that's an unrealistic expectation.

I do want us to write a blog post announcing the release and explaining the new events API, and I would like us to formally deprecate the old formatter API in this release.

Otherwise, I'm happy to release what we have. What do you think @cucumber/cucumber-ruby?

**Comment by brasmusson** [comment]
Several of us is coming to [Cukenfest](https://cukenfest.cucumber.io/), so it seems premature to release before that, but we should come out from there with only a very short list of things to do before releasing 3.0.0. 

Things I wish to be on such a short list would be https://github.com/cucumber/cucumber-ruby/issues/1044, and since I believe that the exit code should be based on the summary - I imagine a new `flaky` category in the summary (as in `6 Scenarios (1 Passed, 1 Failed, 1 Undefined, 1 Pending, 1 Skipped, 1 Flaky)`)

**Comment by danascheider** [comment]
Totally agree with everything @brasmusson said.

**Comment by junaruga** [comment]
Okay, @brasmusson the Cukenfest is June 21st - 25th. So maybe you want to release cucumber 3.0.0 during the event term, right? 

I saw your guys' face photos in the event page. It is in London. It's close from my living country Czech Republic. :) Though I won't attend the event, I hope the event's success. 😄

**Comment by brasmusson** [comment]
v3.0.0 and v3.0.1 are out.
