### ISSUE TITLE
3.0.0.pre.2 - regexp no longer matching correct amount of capture groups

### ISSUE THREAD

**Issue by JeanMertz** [cucumber/cucumber-ruby#1191]
This step definition:

```ruby
Given(/^I have a( trial)? subscription( with (\d+) days left)?$/) do |trial, with_days_left, days_left|
end
```

worked in Cucumber pre 3.0. In the latest 3.0 release, it returns:

```
Your block takes 3 arguments, but the Regexp matched 2 arguments. (Cucumber::Glue::ArityMismatchError)
```

Even though there are clearly three capture groups (does it trip up because of the nested capture?)

**Comment by mattwynne** [comment]
@JeanMertz did you *want* to capture three groups, or are you just noting a change in behaviour?

cc @aslakhellesoy - FYI it looks like the introduction of #1156 might not be fully backward compatible - is that a likely analysis do you think?

**Comment by JeanMertz** [comment]
@mattwynne correct, I want to capture three groups. We solved this for now by splitting up the one step into two, so we don't need the nested regex anymore.

**Comment by aslakhellesoy** [comment]
Looks like a regression. I'll look into this one.

**Comment by aslakhellesoy** [comment]
Ok, this is a backwards-incompatible for sure, but it's by design. Only top level capture groups are counted.

This is a consequence of parameter type transforms being able to handle capture groups. I'll try to explain with a couple of examples.

Both Cucumber Expressions and Regular Expressions are now managed by the `cucumber-expressions` library. One of the things this library lets you do is to define `transformer` functions, for example:

```ruby
ParameterType(
  name: 'colour',
  regexp: /red|blue|yellow/,
  transformer: -> (colour) { Colour.new(colour) }
)
```

You can also use capture groups in the regexp:

```ruby
ParameterType(
  name: 'flight',
  regexp: /(\w+)-(\w+)/,
  transformer: -> (from, to) { Flight.new(from, to) }
)
```

The Cucumber Expression `a {flight}` gets translated to `/^ a ((\w+)-(\w+))/`. This regexp has 3 capture groups, but the library will group them into a tree representing the nesting of the groups. In this case, a tree with 1 child, which has 2 children. Only the top-level groups become arguments to the step definition. If a top-level group has children, they all get passed to the transformer.

Your step definition could be translated to:

```ruby
Given('I have a {subscription}') do |subscription|
end

ParameterType(
  name: 'subscription',
  regexp: /(trial )?subscription(?: with (\d+) days left)?/,
  transformer: -> (trial, days_left) { Subscription.new(!!trial, days_left.nil? ? nil : days_left.to_i) }
)
```
