### ISSUE TITLE
Step definitions with arguments fail with "No self_obj"

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1281]
_From @karlhe on March 1, 2018 0:55_

## Summary

Any cucumber step that matches with a step definition will error out with something similar to this:

```
    When I go to the root page                                # features/step_definitions/web_steps.rb:29
      No self_obj (RuntimeError)
      /Users/karlhe/.gem/gems/cucumber-expressions-5.0.13/lib/cucumber/cucumber_expressions/argument.rb:31:in `value'
      /Users/karlhe/.gem/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:18:in `block in args'
      org/jruby/RubyArray.java:2487:in `map'
      /Users/karlhe/.gem/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:17:in `args'
      /Users/karlhe/.gem/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:97:in `deep_clone_args'
      /Users/karlhe/.gem/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:29:in `invoke'
      /Users/karlhe/.gem/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:24:in `block in activate'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/action.rb:24:in `execute'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:32:in `execute'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:104:in `execute'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:51:in `execute'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:27:in `test_step'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:17:in `describe_to'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:28:in `block in describe_to'
      org/jruby/RubyArray.java:1735:in `each'
      /Users/karlhe/.gem/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:27:in `block in describe_to'
```

Step definition:
```
When(/^(?:|I )go to (.+)$/) do |page_name|
  visit path_to(page_name)
end
```

Started when I upgraded to 3.1.0, does not happen on cucumber-ruby 3.0.2.
Likely has something to do with 3.0.2 using cucumber-expressions-4.0.4, and 3.1.0 using cucumber-expressions-5.0.13

Uses a step definition with no arguments works without any issues.

Possibly related: https://stackoverflow.com/questions/47621315/no-self-obj-runtimeerror-cucumber-capybara-whenever-i-use-double-quotes-on-my

## Your Environment

* Version used: cucumber-ruby 3.1.0
* Operating System and version: macOS 10.13.3
* JRuby 9.1.16.0

_Copied from original issue: cucumber/cucumber#337_

**Comment by aslakhellesoy** [comment]
What version of cucumber-expressions are you on?

Try upgrading to cucumber-expressions 5.0.13

Does that fix it?

**Comment by karlhe** [comment]
The error happens when using cucumber-ruby 3.1.0 and cucumber-expressions 5.0.13
The problem does not occur when using cucumber-ruby 3.0.2 and cucumber-expressions-4.0.4

Let me know if there's any combinations you want me to test.

Versions of related gems if it helps:

```
    cucumber (3.1.0)
    cucumber-core (3.1.0)
    cucumber-expressions (5.0.13)
    cucumber-rails (1.5.0)
    cucumber-tag_expressions (1.1.1)
    cucumber-wire (0.0.1)
    rspec (3.7.0)
    rspec-rails (3.7.2)
```

**Comment by aslakhellesoy** [comment]
I installed jruby-9.1.16.0 and the gems you mentioned above. Then I created an empty cucumber project with `cucumber --init` and added your stepdef and a simple feature file with a matching step. 

No errors. 

Could you please provide an [mcve](https://stackoverflow.com/help/mcve) so we can reproduce this?

**Comment by aslakhellesoy** [comment]
Hi @karlhe - if you can help us reproduce it we'll have a look at fixing this.

**Comment by dennis-d** [comment]
I did some debugging in the environment and it looks like something override '==' method. At least it doesn't behave as intended 

self_obj return world object `step_definition.registry.current_world`, which seens to be the correct bahavior

`<Cucumber::Rails::World+SetupHelpers+GlobalizationHelpers+DatasourceHelpers+GenerateXPath+TemporalHelpers+TableHelper+ResetSchema+SelectorHelpers+NavigationHelpers+JQueryUI+XPath+XPath::DSL+GridHelpers+GraphHelpers+Cleanup+RSpec::Mocks::ExampleMethods+RSpec::Mocks::ArgumentMatchers+Cucumber::Rails::Capybara::SelectDatesAndTimes+Capybara::RSpecMatchers+Capybara::DSL+RSpec::Matchers+Cucumber::Glue::ProtoWorld+#<Module:0x1d07d728>+Rack::Test::Methods+ActionDispatch::Routing::UrlFor+ActionDispatch::Routing::PolymorphicRoutes+ActionController::ModelNaming+ActionController::TemplateAssertions+ActionDispatch::Integration::Runner+ActionDispatch::Assertions+ActionDispatch::Assertions::RoutingAssertions+ActionDispatch::Assertions::ResponseAssertions+Rails::Dom::Testing::Assertions+Rails::Dom::Testing::Assertions::TagAssertions+Rails::Dom::Testing::Assertions::SelectorAssertions+Rails::Dom::Testing::Assertions::SelectorAssertions::CountDescribable+Rails::Dom::Testing::Assertions::DomAssertions+ActiveSupport::Testing::TimeHelpers+ActiveSupport::Testing::Deprecation+ActiveSupport::Testing::Assertions+ActiveSupport::Callbacks+ActiveSupport::Testing::SetupAndTeardown+ActiveSupport::Testing::TaggedLogging+Minitest::Guard+Minitest::Test::LifecycleHooks+Minitest::Reportable+Minitest::Assertions+Sequel::SQL::Constants+PP::ObjectMixin+ActiveSupport::Dependencies::Loadable+RiCal::CoreExtensions::Object::Conversions+JSON::Ext::Generator::GeneratorMethods::Object+Kernel+:0x80c>`

when comparison happens `self_obj == :nil` it returns `XPath::Expression`, which would always be `true`
` pry(#<Cucumber::CucumberExpressions::Argument>)> self_obj == :nil
<XPath::Expression:0x73502c47
 @arguments=[:"=", #<XPath::Expression:0x1871068d @arguments=[], @expression=:this_node>, :nil],
 @expression=:binary_operator>`

`self_obj.equal?(:nil)`  returns false (expected behavior)

**Comment by aslakhellesoy** [comment]
Thanks that sounds plausible @dennis-d. Would you be able to create an mcve, or a failing unit test to make this reproducible?

**Comment by karlhe** [comment]
Sorry I haven't followed up on this, but I finally got around to looking at it a bit.
mcve: https://github.com/karlhe/cuketest

The error is due to bad interaction with this in `env.rb`:
```
module TestModule
  include XPath
end

World(TestModule)
```

```
> rake cucumber
/Users/karlhe/.rubies/jruby-9.2.0.0/bin/jruby -S bundle exec cucumber --profile default
Using the default profile...
Feature: Test

  Scenario: Before setup       # features/test.feature:3
    When I go to the root page # features/step_definitions/test_steps.rb:3
      No self_obj (RuntimeError)
      features/test.feature:4:in `When I go to the root page'

Failing Scenarios:
cucumber features/test.feature:3 # Scenario: Before setup

1 scenario (1 failed)
1 step (1 failed)
0m0.144s
```

This is the XPath module from Capybara: https://github.com/teamcapybara/xpath

With a quick look at what the xpath module does, I can see why this might cause issues.

It's pretty easy to work around on my end, and you guys would know better than me whether this should be considered an issue. It did work in previous versions of cucumber though.
