### ISSUE TITLE
Cucumber returning non-zero exit code when failing test passes on --retry

### ISSUE THREAD

**Issue by Denbeelen** [cucumber/cucumber-ruby#1333]
When i run my test with the command:

cucumber <feature> --retry 1 --color -p default -t @firstrun -f pretty  --format json -o ./reports/test.json

then i see in the json the step that failed first and after the run passed
this results in 

8 scenarios (1 flaky, 7 passed)
28 steps (1 failed, 1 skipped , 26 passed) 

Problem is that in Jenkins cucumber report marks build as failed because 1 step failed.

The json file should only contain the latest run 
so not 1x failed | 1x passed
--> only 1x passed

is this possible?

**Comment by karlhe** [comment]
This also applies to junit output. When retry is on it will create a new `<testcase>` block for each attempt, so if it succeeds on the 3rd retry the junit output shows 2 failures.

**Comment by karlhe** [comment]
Caveat that I'm not the original poster but that's not quite it.

I'm using json or junit output so that Jenkins will parse the results of the test runs accordingly. The problem being that even if a test succeeds on a subsequent retry, the output still contains the earlier failed tries.

I assume the point of the --retry functionality is to account for flappy tests and not fail if it can pass on a retry, however since the failed try is still contained in the output Jenkins treats them as separate tests so it shows up as "1 failed, 1 passed" for example if it passed on the first retry.

The request is for the ability to only put the latest retry attempt in the output.

**Comment by luke-hill** [comment]
Right, ok that's not the way the --retry output works though?? So if that's the Original Poster's intentions then it will likely be closed.

The retry functionality aims to classify tests as flaky by returning them as having previously failed. But 
 then having passed later on. If you want 2 separate reports, there are other ways to do that such as using the --rerun tag which will generate 2 separate sets of tests, and therefore 2 sets of output html / json

@Denbeelen probably worth you chiming in here.

**Comment by SymphonicJohn** [comment]
Two sets of html are not the objective in my use case.
Cucumber formatted xml generate an Allure html report, but my CICD gate between environments only reads junit.
Does anyone have a workaround for handling flaky tests for junit output?
Thanks

**Comment by luke-hill** [comment]
@SymphonicJohn if you have an issue it's probably worth you opening a separate issue

**Comment by danascheider** [comment]
@luke-hill So I'll preface this by saying that my opinion, and I suspect that of the other core maintainers as well, is that flaky features should be fixed or removed and not remain flaky indefinitely. After all, most people wouldn't want to deploy code that sometimes works to production, and "sometimes" is all that a flaky feature guarantees.

All that said, we already have added the `--retry` functionality itself to accommodate flaky features, so in light of that, I'm wondering if we also might add an CLI/`cucumber.yml` option to return a zero exit code when retried scenarios eventually pass. Lots and lots of people use Jenkins (as well as other CI tools that may work the same way), and many of them no doubt also have flaky tests. Do you think this is a significant (and legitimate) enough use case for us to do that?

**Comment by luke-hill** [comment]
I think that's what I hinted at in my interpretation of the issue report.

If you have a situation where you have 4 flaky tests and they pass on --retry, a 0 exit code should be returned.

But given the issue has twisted and turned a bit and I've no idea of the OP intentions, I've no idea what to do here, because it feels like it's 3/4 issues in one.

**Comment by SymphonicJohn** [comment]
Thanks for looking at this. I thought my aim was the same as OP's because we both seem to want a test that passes on retry to not indicate as failed to our pipelines (non zero exit code in their case and failures in the xml in mine). I can open this as a separate ticket if you still feel this is different enough.  

I agree that it would be nice to fix flaky tests so that they don't occur. The source of my occasional failed tests is our [third party cross browser service](https://app.crossbrowsertesting.com/public/ic24f186df9ac369/selenium/17496686/?view=commands) is flaky for some browsers. 

My quick and dirty patch for now is to patch the jUnit formatter to only increment the failure count like below. This only works for a single retry. Is there a variable that can be checked to know if there are retries remaining for a test case? 

`
require 'cucumber/formatter/junit'

def build_testcase(result, scenario_designation, output, test_case)
      duration = Cucumber::Formatter::ResultBuilder.new(result).test_case_duration
      @current_feature_data[:time] += duration
      classname = @current_feature_data[:feature].name
      name = scenario_designation
  
      @current_feature_data[:builder].testcase(:classname => classname, :name => name, :time => format('%.6f', duration)) do
        if !result.passed? && result.ok?(@config.strict)
          @current_feature_data[:builder].skipped
          @current_feature_data[:skipped] += 1
        elsif !result.passed? && !same_feature_as_previous_test_case?(test_case.feature)
          status = result.to_sym
          exception = get_backtrace_object(result)
          @current_feature_data[:builder].failure(:message => "#{status} #{name}", :type => status) do
            @current_feature_data[:builder].cdata! output
            @current_feature_data[:builder].cdata!(format_exception(exception)) if exception
          end
          @current_feature_data[:failures] += 1 
        end
        @current_feature_data[:builder].tag!('system-out') do
          @current_feature_data[:builder].cdata! strip_control_chars(@interceptedout.buffer_string)
        end
        @current_feature_data[:builder].tag!('system-err') do
          @current_feature_data[:builder].cdata! strip_control_chars(@interceptederr.buffer_string)
        end
      end
      @current_feature_data[:tests] += 1
    end
`

Thanks again
