### ISSUE TITLE
Retry does not trigger some formatter methods

### ISSUE THREAD

**Issue by serhatbolsu** [cucumber/cucumber-ruby#1340]
cucumber (3.1.2)

## Summary

I would like to use `--retry`` while having html / or a custom formatter implemented. I have realized
following events does not trigger while retrying a failed test case:
```
before_examples
after_examples
before_table_row
after_table_row
```

## Expected Behavior

I would like to use formatter as while using a test case with examples. Ex.
```
  Scenario Outline: Verify filters in property 'for rent' page
    Given I navigate to a certain page
    When I filter using  "<Filters>" on certain page
    Then I verify the "<Filters>" in certain page
    Examples:
      | Filters      |
      | price_min    |
      | price_max    |

```
## Current Behavior

Table row filter's only trigger for the first run, and does not trigger `before` before the retrying test case.

**Comment by serhatbolsu** [comment]
Hi, what do you think about this, is there a simple solution ? If you point me in correct place, I might work on a PR as well

**Comment by danascheider** [comment]
Thanks for the report @serhatbolsu! I didn't work on the `--retry` feature at the point where the newer formatter API was added, so I'm not sure what the rationale was for not firing these events on retried scenarios. As such, I'm hesitant to say whether we'd accept a PR for this. Do you know what the reasoning behind this was @luke-hill?

**Comment by luke-hill** [comment]
Not sure sorry.

I know there was a separate issue request someone submitted a while ago about the exit code potentially being incorrect. But other than that I'm not sure.

`--retry` was added in cucumber3, and I know it was a first pass approach, and there could be some tweaks made to it. The only caveat to this is I know tables have had a few teething problems going to v3 because not many people use them. Aslak is probably the best person to advise here though. I've never used any of the example hooks you've mentioned, so I can't comment

**Comment by serhatbolsu** [comment]
@aslakhellesoy  need your assistance please
