### ISSUE TITLE
Restore support for Ruby 2.3 and 2.4.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1467]
We recently released `5.0.0` and `5.1.0`. These would have been `4.2.0` and `4.3.0` had it not been for the fact that we dropped support for Ruby `2.3` and `2.4`.

Today I discovered https://stats.rubygems.org/ which suggests 55% of Ruby users are on one of the versions we dropped support for. I hadn't expected that many people to be using unsupported rubies.

I think we should release 5.2.0 where we restore Ruby `2.3` support.

**Comment by aslakhellesoy** [comment]
I also think we should make `4.2.0` and `4.3.0` releases, back-porting what's in `5.0.0` and `5.1.0`.

But for how long do we keep doing these parallel releases?

**Comment by luke-hill** [comment]
Good question, you've opened a bit of a can of worms.

I knew 2.3 / 2.4 were still in use, but I never would have guessed 50%. I think it's a dilemna that perhaps is best served by the rails analogy. So you serve a couple of majors back, but only with critical things.

So we could make 4.2 / 4.3 releases that re-enable lower rubies, but then the new stuff only goes into cucumber5, and any bug fixes can go into 4/5

**Comment by luke-hill** [comment]
Any further thoughts on this. Currently cucumber rails uses 2.4+ and the metrics on that graph over the last month don't really show much change.

The only thing I "would" say is (And I don't know the answer), are those numbers where they are because of people wanting to use those versions, or because CI systems are using those systems and so the numbers are high (Chicken / Egg e.t.c.)

**Comment by aslakhellesoy** [comment]
I hadn't thought of that - high 2.3 and 2.4 numbers possibly due to CI servers using old versions.

**Comment by aslakhellesoy** [comment]
Even if CI servers were using old versions, I doubt it would have much of an impact on the stats. According to the stats the last chart shows that close to 100% of builds are *not CI*, so high numbers of old rubies are almost certainly not due to CIs using them.

**Comment by BrianHawley** [comment]
High 2.3 and 2.4 numbers are probably from people still using  2.3 and 2.4 in their apps. 50% sounds about right for that, especially when you count JRuby 9.1 or earlier users who are stuck on older Ruby version compatibility. Since people could be depending on their cucumber tests to help them verify Ruby updates, not supporting the versions that they're updating from seems a bit counterproductive.

**Comment by aslakhellesoy** [comment]
bump

**Comment by luke-hill** [comment]
Do we have any thoughts on how to tackle this @aslakhellesoy ? Did my rails analogy make sense.

So the 4.x revisions only contain bug fixes, all new functionality goes into cucumber 5.x?

**Comment by aurelien-reeves** [comment]
Restoration of support of ruby 2.3 and 2.4 has not been done after a year now
We did not had any complain

I guess people still relying on those unsupported ruby version are not concerned with upgrading their cucumber either

Do we still want to discuss and/or try re-enabling support for those old rubies?

**Comment by aslakhellesoy** [comment]
Given that we haven't had any complaints, I don't see this as high priority. I'm closing this. We can reopen if someone complains.
