### ISSUE TITLE
CI: Add Ruby 3.0

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-ruby#1498]
In order to see builds run on latest stable release of Ruby, so that I can know if my project can update to that.

I'd like config.yml for CircleCI to include **a build step for 3.0**.

Alternatives: Well, ruby-latest is in there, but I believe we have some "allow failures" enabled for it.

🌮

**Comment by olleolleolle** [comment]
(I labeled this dev experience.)

**Comment by aurelien-reeves** [comment]
@olleolleolle thanks for your suggestion.

May I ask: you are an actual and active contributor to cucumber-ruby. Why didn't you open a PR to submit your idea? Did you wanted to start a discussion about that before submitting it?

**Comment by olleolleolle** [comment]
@aurelien-reeves The project and its relationship to SmartBear has made some things more global to the Whole Project, so small deviations here and there may need more context to not be a problem. As an Issue, there was more room to discuss that, or just Do It, if no known blockers were there. 

In short: I expected blockers.

**Comment by aurelien-reeves** [comment]
Oh...

Please, feel free to contribute as you did before. Regarding Cucumber Open and all that is related, there is no more (hidden or not) context that there were before. Really, feel free to contribute!

If you have any concern, open a PR instead of committing directly to the main branch. But please, do not be afraid to contribute, submit PRs, be active as a contributor. Cucumber Open and all related open components remain an Open Source Software
