### ISSUE TITLE
Is there any way to call log method outside of hooks and step defination

### ISSUE THREAD

**Issue by jigneshmm** [cucumber/cucumber-ruby#1502]
**Describe the bug**
Trying to call log method outside of step definitions and hooks file is not supported but trying to figure out is it possible to call this method
https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/glue/proto_world.rb#L110

I will try and explain why we are trying to do this
We are trying to solve logging at the broad level in our framework, we have multiple logs we display for each step definition currently what we do is to save all logs(Statements) in the variable and then print them as a part of log in hooks.rb after step hook or in the step definition

**Comment by luke-hill** [comment]
Could you not solve this with a regular Ruby Logger? Is there something specific you wish to output into the html report? Or are you just generally looking for log support? It's not really evident from your issue what is the problem.

You're calling the `log` method but struggling? Because inside your classes you're not inside the cucumber world? Could you not just return the value from your method invocation into the step defs again and then log that?

I might be missing something here, but I'm not really sure this is a problem? The `log` method in cucumber is designed to be a way of showcasing simple log messages inside cucumber reports. If you need something much more descriptive, a customised logger would be my advice.

I'll await your response, hopefully I've covered most of the use cases here.

**Comment by jigneshmm** [comment]
Thank you for the quick response @luke-hill 

we were trying to solve our problem with Ruby Logger and upgrading to Cucumber 5 at the same time and we came across the log method.

We are currently calling the log method from hooks and step definitions and it's working perfectly fine, We will try to solve our problem with the custom logger. I asked the question just to confirm that will it be possible to call the cucumber log method from the page classes or not but from the response, it looks like the answer is no.

Our problem is in one step we are logging for example 8 output statements(log) currently we keep pushing them in an array and print them in a cucumber log from afterstep hooks. What we are trying to solve is if my test fails in 6the statement I want 5 statements to pass and then only log 6th statement as an error. I agree it's too much customization from our end. 

We will implement our own custom logger. Thank you again for your quick response.

**Comment by sandeepnagra** [comment]
@luke-hill - if we use custom ruby logger then that log doesn't show up in cucumber reports. Is there any way to get log/text from methods/functions in our page class to cucumber reports?

**Comment by luke-hill** [comment]
You would use the `log` message there inside the cucumber world. I think the OP was wanting something very custom to happen.

If you're wanting simple messages or values to appear in the report, then `log` is the way to go.

**Comment by luke-hill** [comment]
I think we've gone round in circles here a few times.

* If you're looking to do some basic logging i.e. to put in the cucumber report. then use the `log` method.
  * This is a method that works inside the cucumber world. i.e. you must be inside the steps or hooks to do it
* If you're looking to do some more rigorous logging. You should be using the ruby logger utility. This can be extended however you want.

This covers all use cases. If there's something you're not sure about, it is likely going to exist in either the simple use case (In which use the worldable method), or you need to use the existing ruby API.
