### ISSUE TITLE
auto reference scenario in ghekin

### ISSUE THREAD

**Issue by EnriqueRamirezbecxi** [cucumber/cucumber-ruby#1632]
### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by aurelien-reeves** [comment]
I am closing the issue because it is empty

(I could have closed it with no comment explaining why 😅)

Also, If this is a feature request asking for the possibility to kinda "use" a scenario within another one, this is something we are not willing to do. We believe that there are better ways to design features and scenarios that prevent such need. Steps can express a lot more than just an iterative step in the test resulting from your scenario.

I encourage you to take a look here: https://cucumber.io/docs/bdd/better-gherkin/
