### ISSUE TITLE
Cucumber Expressions does not build on Docker - Ruby 3.3

### ISSUE THREAD

**Issue by parholmdahl** [cucumber/cucumber-ruby#1747]
### 👓 What did you see?
I am using a docker file that uses the latest ruby:alpine image and happened to rebuild today. At 25 december ruby released version 3.3 of this image. After that i can not run cucumber getting erromessage: 

`/usr/local/bundle/gems/cucumber-cucumber-expressions-17.0.1/lib/cucumber/cucumber_expressions/group_builder.rb:20: [BUG] Segmentation fault at 0x0031ffff8a2befd0
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux-musl]`

If i set the dockerfile to use ruby 3.2 instead, the issue is gone.

**Comment by luke-hill** [comment]
Will triage this soon. It's only just come out so it's to be expected teething issues will be present.

Thanks for the report @parholmdahl

**Comment by luke-hill** [comment]
Hi @parholmdahl 

I've managed to get one of my local repos working on ruby 3.3.0 same revision as yours `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]`

I have tested with pre-built expressions, no expressions and custom expressions - all seem fine.
I'm unable to debug interactively at the moment due to a bug with RubyMine.

Can you see if you can reproduce and/or upload an MVCE ideally in the form of a pull to this repo or a github repo I can clone
