### ISSUE TITLE
Background not executed for Scenario Outline defined after Scenario in the same Feature file.

### ISSUE THREAD

**Issue by mgrebenets** [cucumber/cucumber-ruby#560]
I have a feature file with both Scenario and Scenario outline.
For example

``` cucumber
Feature: My Feature
  As a user I want...

Background:
  Given the app has launched
  I wait for landing page to appear

Scenario: My Scenario
  Given I am on the landing page
  I do some thing

Scenario Outline: My Scenario Outline
  Given I am on the landing page
  I do <some thing>

Examples:
  | some thing |
  | the thing |
```

So when I run all scenarios from this feature file, I have noticed that the Background is executed for "My Scenario", but not executed for "My Scenario Outline".
The "Given I am on the landing page" step fails for the outline.

If I swap scenario and scenario outline (put scenario outline first in the file), then this problem does not occur.

Is it a known limitation?
Should I always put outlines before scenarios?
Or is it a bug?

**Comment by jorlebarmend** [comment]
I am requesting to re-open this topic because I have recently had the same thing happen - though I cannot discover the root cause. 

Scenario outlines are failing when placed after a scenario in our tests. This is happening on a development laptop (Mac OSX) and also on a staging Jenkins machine (running Linux). 

I came upon this thread after trying several different things to solve this issue. It happened to be that only up until last week this was not an issue, and then tests started to fail consistently in the exact same place. 

I tried the suggestion above of moving the Scenario outline to be the first test after the background and this has solved the issue, however I would like to know if there's a way to discover what the toot cause is. 

Is there any information I could provide that might help diagnose this situation. 

Also I would lie to point out that this is not happening on another development machine, nor on our production/live Jenkins, even when running the same code.

**Comment by mattwynne** [comment]
@jorlebarmend thanks for reporting this.

There are some significant internal changes in version 2.0 of Cucumber that have made lots of bugs like this go away. I'm afraid we won't be making any effort to fix them in the 1.3.x codebase.

Instead, I'd prefer to help get you upgraded. Which reporting gem are you using? Do you know why it's not compatible with 2.0?

**Comment by jorlebarmend** [comment]
@mattwynne the information I have at the moment is that we are using the Json expanded formatter, which we need for the Jenkins cucumber plugin. As far as I know this has not been updated to work with a newer version of cucumber.

**Comment by brasmusson** [comment]
@jorlebarmend Are you talking about the producing json files for the use of [MasterThought Cucumber-Reporting tools](http://www.masterthought.net/section/cucumber-reporting) using the `--expand` option? Which was implemented in v1.3.17 by #700? That functionality is also available in v2.0.0.rc.X.

**Comment by jorlebarmend** [comment]
@brasmusson, unfortunately not bras - we are using the expanded formatter ruby file from this gist

https://gist.github.com/blt04/9866357

**Comment by brasmusson** [comment]
@jorlebarmend Well, since both that formatter and the #700 changes to Cucumbers own json formatter aims at solving the same issue, to produce json files that can be used by the MasterThought Cucumber-Reporting tools - also when using Scenario Outlines, you definitely have the options to upgrade to Cucumber v2.0.0.rc.X (or v1.3.17-19) and use Cucumbers own json formatter to produce json files for you. The limitation you get is that you need to use the `--expand` option when producing those json files. In return you get all the improvements made in the v2.0.0 track.

**Comment by sgran** [comment]
I can confirm that we had the issue with both 1.3.5 and 1.3.10 on linux.  An upgrade to 2.4.0 on linux seems to have resolved it for us.
