### ISSUE TITLE
Failing Scenarios Exiting with 0

### ISSUE THREAD

**Issue by alp06h** [cucumber/cucumber-ruby#635]
Tests are being properly executed, however we have been having the exit 0 message from cucumber no matter if the features are failing or passing. This has been a relatively recent issue. See screenshot below.

![screen shot 2014-02-24 at 1 05 50 pm](https://f.cloud.github.com/assets/1842829/2248882/8928f94e-9d7e-11e3-9031-dbd78ee58635.png)
- TEST_SUITE="bundle exec cucumber path_to_features -r path_to_steps"

ruby 2.1.0
cucumber 1.3.10

**Comment by neoeno** [comment]
Followed this one down the rabbit hole today. Couldn't see any nicer way of doing this in rails than an initializer with the following:

```ruby
if defined? Minitest
  Minitest.module_eval do
    def self.autorun; end
  end
end
```

Looking at multi_test, it seems like it's supposed to do this. Maybe something in minitest changed?

One important thing: it only messes up when running from a rake task, not when run directly from the command line...

**Comment by abinoam** [comment]
I was stuck trying to ```git bisect``` with ```cucumber``` and it kept failing because it always returned zero status code.
Thanks @alp06h hack I was able to figure out the problem.
I've had at ```features/support/env.rb```
```ruby
at_exit do
  DatabaseCleaner.clean_with :truncation
end
```

Changing it to this code bellow (borrowed from @alp06h 's code)
```ruby
at_exit do
  # Preserve exit status
  exit_status = $!.status if $!.is_a?(SystemExit)
  DatabaseCleaner.clean_with :truncation
  exit exit_status if exit_status
end
``` 
... solved the issue.

I'm on:
* Ruby 2.2.2
* Cucumber 2.3.2
* Rails 4.2.5.1
* Database Cleaner 1.5.1

Note: at_exit hook is recommended by the Cucumber github developers.
See: 
* https://github.com/cucumber/cucumber/wiki/Hooks#global-hooks
* https://www.ruby-forum.com/topic/178689

**Comment by dwickwire** [comment]
What version of cucumber-ruby is this going to end up in?

Is cucumber-ruby part of  `'cucumber', '2.3.3' or `'cucumber-rails', '1.4.3'` or `"database_cleaner", "1.3.0"`?  I use those and have this problem too but I don't see cucumber-ruby as part of those.  Do I need to open an issue somewhere else?  Where might that be?

**Comment by dg-ratiodata** [comment]
@dwickwire Don't be confused. https://github.com/cucumber/cucumber-ruby is the ruby-gem "cucumber". See [the gemspec](https://github.com/cucumber/cucumber-ruby/blob/master/cucumber.gemspec)-file.
