### ISSUE TITLE
Usage formatter still `@wip-new-core`

### ISSUE THREAD

**Issue by tooky** [cucumber/cucumber-ruby#877]
Noticed this scenario still has `@wip-new-core` tagged. It doesn't pass.

https://github.com/cucumber/cucumber-ruby/blob/8b5b9bd4b542e4df35cfdba10c666d1b695c560d/features/docs/formatters/usage_formatter.feature#L33

**Comment by brasmusson** [comment]
Going back to v2.0.0 that scenario really failed, the expanded/instantiated steps from the Scenario Outline was not included - due to that the formatters using the old formatter api never get to know about the steps for the Scenario Outline scenarios (in non-expanded mode).

Now when the usage formatter has been rewritten to use the new formatter api (#859), the scenario actually passes - after taking into account the duration is not printed in quiet mode (#822), and that the progress formatter now prints a `.` for every executed step (changed in [#859](https://github.com/cucumber/cucumber-ruby/pull/859#issue-82864181))

**Comment by tooky** [comment]
@brasmusson :bow: thanks!

I spotted it while working on something else and made an issue so I didn't forget!

**Comment by brasmusson** [comment]
@tooky This should of course have been fixed in #859, how the person who did #859 missed that is beyond me :smile:
