### ISSUE TITLE
Cucumber 2.0.1 - Windows - Unable to run from anywhere but C drive

### ISSUE THREAD

**Issue by janahanEDH** [cucumber/cucumber-ruby#885]
I'm using Cucumber 2.0.1, Ruby 2.1.5, Windows 7.
This used to work fine on Cucumber 2.0.0.

If you try to run tests from a drive other than the C drive (My workspace is on the D drive), you get this:
```
different prefix: "C:/" and "d:/cuke_test" (ArgumentError)
C:/Ruby21/lib/ruby/2.1.0/pathname.rb:503:in `relative_path_from'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/hooks.rb:32:in `location'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/prepare_world.rb:28:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/activate_steps.rb:8:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/quit.rb:11:in `test_case'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/case.rb:21:in `describe_to'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/compiler.rb:23:in `done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/gherkin/parser.rb:31:in `done'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:29:in `parse'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:18:in `compile'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/runtime.rb:70:in `run!'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/lib/cucumber/cli/main.rb:38:in `execute!'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/cucumber-2.0.1/bin/cucumber:9:in `<top (required)>'
C:/Ruby21/bin/cucumber:23:in `load'
C:/Ruby21/bin/cucumber:23:in `<main>'
```

**Comment by brasmusson** [comment]
Oops! Actually it is not "drive other than the C drive", but "drive other then where the Cucumber-Ruby gem is installed", as far as I can tell. Most likely the same error would occur (and also in Cucumber v2.0.0), when trying to require step definitions from another drive then the workspace (current directory).

**Comment by mattwynne** [comment]
Thanks for reporting this so promptly!

It looks like there used to be a bug with this in a much earlier version of Ruby - https://redmine.ruby-lang.org/issues/1366 - but it was fixed.

See also http://stackoverflow.com/questions/669417/ruby-relative-path-from-call-on-windows.

**Comment by brasmusson** [comment]
The issue https://redmine.ruby-lang.org/issues/1366 was about mistake "C:\" and "c:\" (different capitalization) for different drives. Here we actually have different drives, so to me it looks like `relative_path_from` cannot work in this situation.

Exploring how the path in the location for step definitions (most commonly) are calculated [cucumber/core_ext/proc.rb](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/core_ext/proc.rb#L16-L27) reveals that relative path is used only when the step definition is located below the current directory in the file system, otherwise absolute path is used (and something third, which I cannot work out, happens when the step definition is loaded from an installed gem). For instance:
```
/<path>/workspace$ cucumber -r ../global_step_defs features
```
will result in that the step definitions form the global_step_defs directory will be printed by the Pretty formatter as something like:
```
    Given <some step>       # /<path>/global_step_defs/<file>.rb:<line>
```
Doing the same for the location for [hooks](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/hooks.rb#L32) (and [step definitions base on symbols](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/hooks.rb#L32)) would fix this issue.
