### ISSUE TITLE
Remove support for Ruby 1.9.3 and below

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#902]
Any objections?

**Comment by akostadinov** [comment]
Depends on when 3.0 is going to be released. We have an older test suite that's perhaps going to live for another 2 years. I guess it wont need new features though so even if 3.0 is released in the following months, I guess 2.x would be solid enough to have it going long enough.

**Comment by tooky** [comment]
It's worth noting that 1.9.3 has been end of lifed, so it's no longer supported by Ruby.

**Comment by akostadinov** [comment]
but still supported by in enterprise linux distributions

**Comment by mattwynne** [comment]
@myronmarston what are your thoughts on this? You need Cucumber in order to run your test suite, right? How long are you going to keep supporting old Rubies?

**Comment by myronmarston** [comment]
> @myronmarston what are your thoughts on this? You need Cucumber in order to run your test suite, right? How long are you going to keep supporting old Rubies?

RSpec is still on cucumber 1.x because we still support 1.8.7, 1.9.2, 1.9.3, and all 2.x versions.  In general:

* We treat the supported ruby versions as part of SemVer, meaning the only time we drop support for old versions is when a new major RSpec version comes out.
* We don't like putting gem authors in the position of having to choose between dropping support for an old ruby version before they are ready (in order to upgrade RSpec) or staying on an old RSpec version, so we support old versions long after the ruby core team has stopped supporting them.  This is particularly important for some gems like bundler, which still supports 1.8.7 and 1.9.2 and uses RSpec.

In RSpec 4, we will definitely drop support for 1.8.7, and perhaps 1.9.2 and 1.9.3 (although that's much less likely).

It looks like cucumber 2.x only supports 1.9.3+, right?  So I guess we are going to be stuck on cucumber 1.x for the foreseeable future.  Honestly, we haven't had any cucumber pain points that have encouraged us to upgrade, anyway.  Hopefully cucumber 1.x will continue working with new ruby versions (e.g. 2.3)?  We might get in a bind if changes in ruby 2.3 are incompatible with cucumber 1.x where there's no cucumber versions that runs on all ruby versions we support.  It makes me think we might want to explore upgrading to cucumber 2.x for the ruby versions that can run it.  Is it easy to have feature files and step definitions that work on cucumber 1.x and 2.x at the same time?

**Comment by mattwynne** [comment]
myronmarston commented on Aug 12

> Is it easy to have feature files and step definitions that work on cucumber 1.x and 2.x at the same time?

Yes, our intent with 2.0 was that it remained completely backwards compatible. I'd expect the step definitions to remain so for quite a few major versions - it's more the "semi-internal" APIs that we're tidying up, making things more modular / plug-able. Remember that thing we broke in one of VCR's Before hooks for example. That kind of thing.
