### ISSUE TITLE
Background running again in scenario causing tests to fail

### ISSUE THREAD

**Issue by ifemagentys** [cucumber/cucumber-ruby#913]
Hello,

I running tests on a mobile app and there seems to be a problem with the background. I think this error is within cucumber. As you can see on the images below, I'm running multiple tests with a background. However when the first scenario runs it fails because it runs the background again within the scope of the scenario after already running it. 
I.e. In the Log In scenario, it is running the "Given I have accepted terms and conditions" step again even though it is not stated in this scenario and it has already run in the background.
The wierd thing is when I run the scenario in isolation, it runs perfectly.

Have you encountered this problem before? Is this a problem within cucumber?
![screen shot 2015-09-11 at 11 54 33](https://cloud.githubusercontent.com/assets/11632499/9813308/4dbfc5c6-587c-11e5-9db8-83f230c20107.png)
![screen shot 2015-09-11 at 11 57 08](https://cloud.githubusercontent.com/assets/11632499/9813306/4bd02512-587c-11e5-8ba3-03fd1ef513d7.png)

**Comment by ifemagentys** [comment]
@mattwynne

**Comment by mattwynne** [comment]
Which version of Cucumber are you using? We had some odd problems like this with the 1.x series but I'd be surprised to see anything like this with 2.x

Would you be able to create a simple way for us to reproduce this? Perhaps a very small repo? It might help you to diagnose / isolate where the problem is anyway.

**Comment by ifemagentys** [comment]
Ah I'm using 1.3. So I will update and let you know if the problem still persists. 

Thanks

**Comment by dzzh** [comment]
I have currently catched this issue in one of my project that uses Calabash with Cucumber 1.3. After I removed an HTML formatter that was configured with --format 'Calabash::Formatters::Html' -o <%= html_report %>, the issue was gone.

You might want to check the formatters you have, it is reported at https://github.com/cucumber/cucumber-ruby/issues/892 that they can cause issues with background steps.

**Comment by ifemagentys** [comment]
Updated my cucumber and it works now. Thanks
