### ISSUE TITLE
Formatter not returning correct status for Scenarios

### ISSUE THREAD

**Issue by cheezy** [cucumber/cucumber-ruby#937]
I believe that the Formatter is returning the status of the last step instead of the overall status for a Scenario in the after_fature_element callback.  For example, if the scenario has two steps and the first one fails then the second step is skipped.  In this example, the scenario is reporting skipped instead of failed.

**Comment by mattwynne** [comment]
Can you give that a try @cheezy?

I saw `undefined` rather than `skipped` status, but that might have been a poor test case. Anyway I'm  hopeful that will fix it for you.

FYI, it would be better to be building against the [new formatter API that just uses test case events](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/extending_cucumber/custom_formatter.feature#L12) - we're going to rip out this old formatter stuff into a opt-in gem from v3.0.

**Comment by cheezy** [comment]
It works perfect now.  Thanks for the fast turnaround.  I'm trying to get my pretty_face gem quickly working with the legacy api.  During the holiday break I plan to look at the new api.

**Comment by cheezy** [comment]
Any idea when this will be released?

**Comment by mattwynne** [comment]
Friday if things go to plan.

**Comment by mattwynne** [comment]
I think this is out now in v2.2 Cheezy - want to give it a go?
