### ISSUE TITLE
Features always run in alphabetical order even when order=random

### ISSUE THREAD

**Issue by threedaymonk** [cucumber/cucumber-ruby#969]
My test suite crashes PhantomJS about ⅔ of the way through the run on a hosted continuous integration service. In order to debug this, I want to try running my scenarios in a random order, so I turn to the `--order=random` option, which is explained as

> Shuffle scenarios before running.

What I expected:

* Scenarios run in random order

What I observed:

* Scenarios run in random order _within_ a feature
* But features always run in alphabetical order

i.e.:

```
Feature: 1

  Scenario: 1B      # features/1.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

  Scenario: 1A      # features/1.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

Feature: 2

  Scenario: 2A      # features/2.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

  Scenario: 2B      # features/2.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

Feature: 3

  Scenario: 3B      # features/3.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

  Scenario: 3A      # features/3.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

6 scenarios (6 passed)
6 steps (6 passed)
0m0.012s

Randomized with seed 8565
```

The [documentation](https://www.relishapp.com/cucumber/cucumber/docs/cli/randomize) only discusses a single feature, so I don't know whether this is the intended behaviour. It wasn't the behaviour that I expected.

The `Randomizer` filter does indeed shuffle the scenarios, but a later filter (I haven't investigated exactly which one or ones) in `Cucumber::Runtime#filters` groups the scenarios by feature and orders the features alphabetically by file path.

Complete randomisation can be achieved by moving the `Randomizer` filter to the last position in the filter chain in the `filters` method, which gives the kind of result I expected:

```
Feature: 1

  Scenario: 1A      # features/1.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

Feature: 2

  Scenario: 2B      # features/2.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

  Scenario: 2A      # features/2.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

Feature: 1

  Scenario: 1B      # features/1.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

Feature: 3

  Scenario: 3A      # features/3.feature:3
    Then do nothing # features/step_definitions/steps.rb:1

  Scenario: 3B      # features/3.feature:6
    Then do nothing # features/step_definitions/steps.rb:1

6 scenarios (6 passed)
6 steps (6 passed)
0m0.011s

Randomized with seed 38210
```

Personally, I think that complete randomisation is more useful than randomisation only within features, but, whichever is chosen, it would be very useful for the behaviour across multiple features to be specified.

I'd be happy to work on this if there's a consensus on what the desired behaviour is.

**Comment by mattwynne** [comment]
Well spotted @threedaymonk, this is not the indented behaviour.

I like to think it's a regression :) maybe caused by the changes made to resolve #901 but as you rightly pointed out the acceptance test for random only uses a single feature so we can't easily tell if this ever worked properly.

I'd be delighted if you could help work on this. It seems like you have a pretty good handle on how to do it but do let me know if you need any help, either with a mention in here or grab me on [Twitter](http://twitter.com/mattwynne) or in the [gitter chatroom](https://gitter.im/cucumber/cucumber-ruby).

**Comment by brasmusson** [comment]
> moving the `Randomizer` filter to the last position in the filter chain in the `filters` method

As the `Randomizer` filter is of the kind that it does not pass the test cases on until `done` is called, it cannot be moved to the last position in the filter chain, since other filters (like the [`Quit` filter](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/filters/quit.rb)) relies on that the test cases is not buffered up after them in the chain. Since it looks like the `LocationsFilter` is the problem in this case, either it is moved to before the `Randomizer` filter in the chain. Or the `Randomizer` filter is moved to directly after the selection filters (`TagFilter`, `NameFilter' and `LocationsFilter`). To first select and then randomize seems reasonable.

**Comment by threedaymonk** [comment]
@brasmusson Thanks, that's very useful.
