### ISSUE TITLE
Cucumber Dry-Run Formatter To Output Which Files Have The Offending Undefineds

### ISSUE THREAD

**Issue by Carlbc18** [cucumber/cucumber-ruby#995]
## Summary

When running cucumber -d on my project if my project has thousands of features the terminal buffer is impossible to scroll back through to determine which feature or steps file has the offending problems.   
## Expected Behavior

It would be great if the formatter could output and the end which files had the offenses. 
## Current Behavior

The formatter outputs that there are for example:
1 Undefined Scenario
34 Undefined Steps 

but includes no file paths.  It could be nice if it could include those offending paths. 
## Possible Solution

haven't given it much thought
## Steps to Reproduce (for bugs)

create a huge feature set with undefined steps and features
run cucumber -d 
## Context & Motivation

Trying to resolve undefined steps and scenarios.  We have a jenkins job which does a dry-run as a last resort to prevent a merge with incomplete work  - can never be too safe. 
## Your Environment

Version: Cukes 2.3.0
Ruby: 2.3.0
Env: Linux & Mac

**Comment by danascheider** [comment]
@Carlbc18 - I really like this idea and had been thinking about it for a while myself. Is this something you'd be able to work on? I'm not sure offhand what the implementation would look like, but I'd be happy to help figure it out, as would the other maintainers.

**Comment by enkessler** [comment]
I feel like it should be an easy enough change because the file and line numbers are already tracked and displayed for failing tests. This seems like it would just be a slightly different condition.

**Comment by danascheider** [comment]
Ah yes, so they are. I was thinking of a slightly different feature, where the output of failing features would be displayed at the end, like failing RSpec tests do. Yeah, tracking undefineds should not be that hard.

**Comment by Carlbc18** [comment]
@danascheider I would definitely be willing to collaborate on this with you. I'm not sure how much time i have at the present to determine how to fix it, but we could talk offline.  Feel free to reach out to me to discuss my email is in my profile.

**Comment by danascheider** [comment]
Cool, will do.

**Comment by brasmusson** [comment]
To see whether there are no scenarios with undefined steps, or there are at least one scenario with undefined steps, you can use `--dry-run --strict`. If the exit code is 0 then there is no scenarios with undefined steps, and if the exit code is not 0 then there is at least one scenario with undefined steps.

Cucumber-Ruby is listing the failed steps and the failed scenarios (if any) at the end (or more precisely, it is listing the command lines to execute each of the failed scenarios):
```
Failing Scenarios:
cucumber examples/i18n/en/features/addition.feature:15 # Scenario Outline: Add two numbers, Examples (#1)

4 scenarios (1 failed, 3 passed)
16 steps (1 failed, 15 passed)
```
The problem is that Cucumber-Ruby is *only* listing the failed scenarios, not all the scenarios that each would have forced the exit code to be non-zero (in `--strict` mode also pending and undefined results are considered to be not ok, as in [Result#ok?](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/result.rb#L157)).

When I implemented a similar listing of "not ok" scenarios in Cucumber-JVM, I included all the scenarios that caused the exit code to be non-zero:
```
Failed scenarios:
cucumber/examples/java/calculator/basic_arithmetic.feature:30 # Scenario Outline: Many additions

Pending scenarios:
cucumber/examples/java/calculator/basic_arithmetic.feature:7 # Scenario: Addition

Undefined scenarios:
cucumber/examples/java/calculator/basic_arithmetic.feature:12 # Scenario: Another Addition

14 Scenarios (1 failed, 1 pending, 1 undefined, 11 passed)
66 Steps (1 failed, 1 pending, 1 undefined, 63 passed)
```

With `--dry-run --strict`, you then only get the scenarios with undefined steps:
```
Undefined scenarios:
cucumber/examples/java/calculator/basic_arithmetic.feature:12 # Scenario: Another Addition

14 Scenarios (13 skipped, 1 undefined)
66 Steps (65 skipped, 1 undefined)
```

The same logic could be implemented in Cucumber-Ruby.

**Comment by enkessler** [comment]
@brasmusson Wow. How did I forget about the ```--strict``` flag? Your Cucumber-JVM behavior sounds like exactly what we are looking for.

@cucumber/core Side note that we can take offline: What's the feasibility of reliably standardizing behavior across different language implementations of Cucumber kind of like how Gherkin has a common spec across languages? Presumably there may be some behavior that can't be done in all implementations due to language limitations but we could at least cover the CLI stuff like this particular case, yes?

**Comment by danascheider** [comment]
@enkessler (1) I forgot about it too. D'oh. (2) Love that idea, that was something that had been bothering me as well.
